### ISSUE TITLE
Activity 4.01 does not work with Django3.2 (as soon as downgrading to Django3.1, it worked)

### ISSUE THREAD

**Issue by oeawFebe** [PacktPublishing/Web-Development-with-Django#1]
Given that your book says "While we can never be 100% certain, we are confident that this code will work fine with future versions of Django too." (p.37), I humbly would like to see the workaround code (or explanation of reason why it does not work with Django3.2). I like your book so much.

Thank you.  Error code I got with Django3.2 is as follows:

```

(venv) Path\to\comment8or>python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Owner\Desktop\comment8or\venv\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Owner\Desktop\comment8or\venv\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Owner\Desktop\comment8or\venv\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "C:\Users\Owner\Desktop\comment8or\venv\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\Owner\Desktop\comment8or\venv\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Owner\Desktop\comment8or\venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Owner\Desktop\comment8or\venv\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\Owner\Desktop\comment8or\venv\lib\site-packages\django\apps\config.py", line 149, in create
    raise RuntimeError(
RuntimeError: 'messageboard.apps' declares more than one default AppConfig: 'AdminConfig', 'MessageboardAdminConfig'.


```

**Comment by arunkhattri** [comment]
Same here, having django 3.2
after completing Subclassing AdminSite and before Activity 4.01 
`python manage.py runserver`
gives following RuntimeError:
`RuntimeError: 'reviews.apps' declares more than one default AppConfig: 'AdminConfig', 'ReviewsAdminConfig'`
struggling to find a solution...

**Comment by arunkhattri** [comment]
Okay got it...
set AppConfig.default to False...
`class ReviewsConfig(AppConfig):
....
default = False`

[reference](https://docs.djangoproject.com/en/3.2/ref/applications/)

**Comment by orlandocarnate** [comment]
I'm also using Django 3.2 and have the same Runtime error regarding `AdminConfig` and `ReviewAdminConfig`

I managed to get it to work by creating a new `apps.py` file in the project root folter after looking at [Overriding the default admin site](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#overriding-the-default-admin-site)

Instead of modifying `reviews/apps.py` I created a new `apps.py` in the root project folder with only the following code:
```
from django.contrib.admin.apps import AdminConfig

class ReviewsAdminConfig(AdminConfig):
    default_site = 'admin.BookrAdminSite'
```

Then in `settings.py` under `INSTALLED_APPS`  I replaced `'django.contrib.admin',` with `'apps.ReviewsAdminConfig',`

**Comment by arunkhattri** [comment]
> I'm also using Django 3.2 and have the same Runtime error regarding `AdminConfig` and `ReviewAdminConfig`
> 
> I managed to get it to work by creating a new `apps.py` file in the project root folter after looking at [Overriding the default admin site](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#overriding-the-default-admin-site)
> 
> Instead of modifying `reviews/apps.py` I created a new `apps.py` in the root project folder with only the following code:
> 
> ```
> from django.contrib.admin.apps import AdminConfig
> 
> class ReviewsAdminConfig(AdminConfig):
>     default_site = 'admin.BookrAdminSite'
> ```
> 
> Then in `settings.py` under `INSTALLED_APPS` I replaced `'django.contrib.admin',` with `'apps.ReviewsAdminConfig',`

its working...Thanks for the solution...

**Comment by oeawFebe** [comment]
> 
> 
> > I'm also using Django 3.2 and have the same Runtime error regarding `AdminConfig` and `ReviewAdminConfig`
> > I managed to get it to work by creating a new `apps.py` file in the project root folter after looking at [Overriding the default admin site](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#overriding-the-default-admin-site)
> > Instead of modifying `reviews/apps.py` I created a new `apps.py` in the root project folder with only the following code:
> > ```
> > from django.contrib.admin.apps import AdminConfig
> > 
> > class ReviewsAdminConfig(AdminConfig):
> >     default_site = 'admin.BookrAdminSite'
> > ```
> > 
> > 
> > Then in `settings.py` under `INSTALLED_APPS` I replaced `'django.contrib.admin',` with `'apps.ReviewsAdminConfig',`
> 
> its working...Thanks for the solution...

It worked for me too. Thank you very much!
