### ISSUE TITLE
Activity5.01 logo.png from reviews app

### ISSUE THREAD

**Issue by petrenkonikita112263** [PacktPublishing/Web-Development-with-Django#15]
I have checked many items, but the logo with the word reviews isn't loaded in base.html inside reviews app. The image from home page is still the same logo.png in all pages. 

![project_structure](https://user-images.githubusercontent.com/56109799/133228025-1ef1d01e-42a4-457b-8151-5bfa9e9b3230.png)

Also, I tried to change STATICFILES_DIRS in settings.py even using the solution configuration didn't help, neither 
`STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'reviews/static/')
]`
or
`STATICFILES_DIRS = [
    BASE_DIR / "static",
    'reviews/static',    # ("reviews", "full_path_to_static_folder")
]`

**Comment by beneboy** [comment]
Hi there, your two `logo.png` files will conflict. The path for the one in the reviews app should be `reviews/static/reviews/logo.png`. This is for namespacing. Then when including in your template, use `reviews/logo.png` as the path.

**Comment by petrenkonikita112263** [comment]
> Hi there, your two `logo.png` files will conflict. The path for the one in the reviews app should be `reviews/static/reviews/logo.png`. This is for namespacing. Then when including in your template, use `reviews/logo.png` as the path.

I made it, but still the image doesn't change.

In reviews/templates/reviews/base.html
`
{% extends 'base.html' %}
{% load static %}
{% block brand %}
    <img src="{% static 'reviews/logo.png' %}" alt="logo_reviews">
{% endblock %}
`

In bookr/templates/base.html
`
{% block brand %}
                <img src="{% static 'logo.png' %}" alt="book_logo">
              {% endblock %}
`

I still see the image logo.png in other pages.

**Comment by beneboy** [comment]
Without seeing your whole project it's hard to tell what's wrong.

You have different `alt` tags for each logo which might help you track it down. Try viewing the source on each page with a logo, and see if the alt tag matches the logo you expect. This will help you tell if it's a template problem or static files problem.

Check that your templates are inheriting from the right base, i.e. your reviews templates extend from the reviews `base.html`. If your review's `base.html` extends the main `base.html`, but none of the other templates extend the reviews `base.html` then they'll still pick up the main logo.

Finally you can use the [`findstatic`](https://docs.djangoproject.com/en/3.2/ref/contrib/staticfiles/#django-admin-findstatic) command to check which files are being found for each URL.

**Comment by petrenkonikita112263** [comment]
> Without seeing your whole project it's hard to tell what's wrong.
> 
> You have different `alt` tags for each logo which might help you track it down. Try viewing the source on each page with a logo, and see if the alt tag matches the logo you expect. This will help you tell if it's a template problem or static files problem.
> 
> Check that your templates are inheriting from the right base, i.e. your reviews templates extend from the reviews `base.html`. If your review's `base.html` extends the main `base.html`, but none of the other templates extend the reviews `base.html` then they'll still pick up the main logo.
> 
> Finally you can use the [`findstatic`](https://docs.djangoproject.com/en/3.2/ref/contrib/staticfiles/#django-admin-findstatic) command to check which files are being found for each URL.

Quite a lot of time it'd taken, but I managed it by copying this from repository settings.py

`STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]`

Without this my app could find static files from reviews app or other, but I'd got the error from root (bookr) static folder.

**Comment by ProgrammerSteve** [comment]
I just had the same issue but realized that my view function in views.py was pointing towards base.html in the root folder when it should have been pointing at the base.html file in the reviews/templates directory. That's where I screwed up.

**Comment by arunspacek** [comment]
@petrenkonikita112263 Hello, mate. I know the answer to your problem.
Open the other two templates inside 'reviews/templates/reviews'
(They are named "book_list.html" and "book_detail")
These two templates extends the project level "base.html".

What you need to do is replace this:

{% extends 'base.html' %}

With this:

{% extends 'reviews/base.html' %}

The cause of the problem is when the authors asked us to move the "base.html" to project-level 'templates' directory and create a new "base.html" inside 'reviews/templates/reviews', they forgot to tell us that we should make the "book_detail.html" and "book_list.html" extend the "reviews/base.html".

Don't forget to let me know if it works.
