### ISSUE TITLE
Activity 17.1 solution for Glances v3.1.3 with psutil v5.5.1

### ISSUE THREAD

**Issue by paxcodes** [PacktPublishing/Web-Development-with-Django#18]
When I try the solution `glances --disable-memswap --theme-white` as seen in the [pdf](https://github.com/PacktPublishing/Web-Development-with-Django/blob/6a002b5407901a679d6f781be91027720bbec58c/Activity_Solutions/Activity-Solutions-for-Web-Development-with-Django.pdf) I encountered the error `unrecognized arguments`. The version I have is the following,

```
pax@bookr:~$ glances -V
Glances v3.1.3 with psutil v5.5.1
```

I also have the latest Ubuntu live server installed: 20.04.3 LTS

My solution was `glances --theme-white --disable-plugin memswap` and I think it's correct given the similarity in the screenshot. To figure out the name of the module, I used the argument `--modules-list`.

![Screenshot 2021-10-19 235704](https://user-images.githubusercontent.com/13646646/138043301-5c445757-db50-46ac-98b6-197e29c1e9a5.png)

Sharing it here in case someone else encounters this, or to notify authors of the change in case PDF can be updated.

**Comment by beneboy** [comment]
Thanks for finding this out. As I understand any fixes like this will be in the next edition, or some errata might be published.
