### ISSUE TITLE
Working on chapter 9 ERROR: Reverse for 'index' not found. 'index' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by Orphan-Crippler** [PacktPublishing/Web-Development-with-Django#24]
So I am working through chpt. 9 everything is going fine. Until I get to the exercise about making the logout page work. So after following exercise 9.04 I click to logout and get this error.

Reverse for 'index' not found. 'index' is not a valid view function or pattern name.

Error during template rendering
In template C:\Users\jlow\django\bookr2\templates\base.html, error at line 7

Reverse for 'index' not found. 'index' is not a valid view function or pattern name.

Here is line 7 from base.html

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

Now I can get it to display the admin logout page if I move the registration templates folder to bookr/reviews/templates/registration. everything else seems to still work fine but the logout page is still the admin one. This was how I originally had this setup because it seemed like that was where the author wanted me to put it. Anyway after looking over the files on github I realized I had placed the registration templates folder in the wrong templates folder and I moved it to the correct one. But now when I click logout I get the error. I have compared pretty much all my files to the ones here on github and they are pretty much the same. I have even gone as far as to copy and paste from github into my project and still get the same error. The only way I have been able to see it work correctly is by downloading the files from github and running the project from them. I am at a total loss here and I know its got to be something stupid I did to get this to happen. If anyone would like to see some of my files from the project please let me know which ones and I will put them here.

**Comment by beneboy** [comment]
Hi @Orphan-Crippler, try adding a name to your index url pattern.

Change:
`path("", reviews.views.index),`

to 

`path("", reviews.views.index, name="index"),`

The `{% url %}` template tag will be looking for a pattern by name but is unable to find it.

**Comment by Orphan-Crippler** [comment]
So that definitely made it work. Thank You so much.

But do you know why when I use the project files from github it works but there is no name on that same url pattern? I did install Django 3.01 like the book said to make things slightly easier on myself.

Just to clarify when I use the files from github I am copying the final folders up to chapter 9 into it's own bookr directory.

**Comment by beneboy** [comment]
@beneboy We may have missed a couple of things, but we're currently working on the second edition to fix these mistakes.
