### ISSUE TITLE
RuntimeWarning: DateTimeField Review.date_edited received a naive datetime (2020-01-04 16:31:40.376237) while time zone support is active.

### ISSUE THREAD

**Issue by paxcodes** [PacktPublishing/Web-Development-with-Django#7]
When running `loadcsv` command, I get this error.

I'm using python 3.9.6

**Relevant links:**

https://docs.python.org/3/library/zoneinfo.html
https://www.python.org/dev/peps/pep-0615/

**Comment by beneboy** [comment]
Thanks for the feedback! For the purposes of this data the timezone isn't too important so the warning can be ignored.

**Comment by paxcodes** [comment]
I reviewed the preface and it didn't mention anything about python versions "supported" by the book so I thought I mention it here in case other people run into it.

Thanks for taking the time to respond!
